[package]
name = "destiny_vendor_rank"
version = "0.1.0"
authors = ["Nolan Brubaker <nolan@nbrubaker.com>"]

[dependencies]
hyper = "0.11.2"
reqwest = "0.7.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
